title: "Shaohui's blog"
description: "AI时代的“自留地”"
url: "https://shaohui1977.github.io"
baseurl: ""

theme: jekyll-theme-primer

markdown: kramdown
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
